name: must run on custom runner
on: push
jobs: 
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
            shell: /usr/bin/bash -e {0}
    env:
    pythonLocation: /home/jsri/actions-runner/_work/_tool/Python/3.8.18/x64
    LD_LIBRARY_PATH: /home/jsri/actions-runner/_work/_tool/Python/3.8.18/x64/lib
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name:Create zip bundle
        run:|
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name:Archive artifact
        uses:actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
     
