name: env var
on: 
  push:
jobs: 
 build:
  runs-on: ubuntu-latest
  env:
     App_mode: ${{ var.App_mode }}
  steps:
   - name: declaring env var  
     run: |
      echo "this is my $App_mode mode"
