name: github pages
on:
  push:
   branches: 
     - lab
jobs:
  build:
   runs-on: ubuntu-latest
   steps: 
    - name: checkout code
      uses: actions/checkout@v4
    - name: setup node.js
      uses: actions/setup-node@v4
      with: 
        node-version: 20
    - name: install dependencies
      run: npm install
    - name: build the webpages
      run: npm run build
    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v4
      with: 
        github_token: ${{ secret.github_token }}
        publish_dir: ./build

     
       
    
     
     
  
 
