name: Greeting
on: 
 push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4
     - name: greeting a person 
       env:
        my_name: Jayasri
       run: |
        echo "Hi add-mask $my_name"
        

     
    
    
     
