name: greet
on: 
 push: 
  branches: 
   - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: checkout a code
      uses: actions/checkout@v4
    - name: greeting a person
      run: |
         echo "Hello my name is ${{ github.actor }}
    
    
     
