name: manualworkflow
on: 
 workflow_dispatch:
 inputs: 
   environment:
     discription: "environment to deploy"
     required: true
jobs:
  manualworkflow:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repository
      uses: actions/checkout@v4
    - name: show info 
      run: |
         echo "run echo"
