name: manualworkflow
on: 
 workflow_dispatch:
  inputs: 
   param1:
      description: "environment to deploy"
      required: true
      default: "Hello"
jobs:
  manualworkflow:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repository
      uses: actions/checkout@v4
    - name: show info 
      run: |
         echo "running manual task with param1: ${ github.event.inputs.param1 }"
