name: manualworkflow
on: 
 workflow_dispatch:
jobs:
  manualworkflow:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout repository
    - uses: action/checkout@v4
    - name: show info 
      run: |
         echo "run echo"
