       name: Set color
       on: push
       jobs:
        build:
         runs-on: ubuntu-latest
         steps:
          - name: checkout code
            uses: actions/checkout@v4
          - name: set color  
            id: color-selector
            run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
            run: echo "SELECTED_COLOR=Black" > "$GITHUB_OUTPUT"
          - name: Get color
            env:
             SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
            run: echo "The selected color is $SELECTED_COLOR"
