name: s3 bucket
on: push 
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: set up nodejs
     uses: action/setup-node@v3
     with: 
       node-version: 20
   - name: install dependencies
     run: npm install
   - name: run the nodejs
     run: npm run build
   - name: download artifacts
     uses: actions/download-artifact@v4
     with:
      name: zipped bundle
   - name: configure aws cli
     uses: aws-actions/configure-aws-credentials@v2
     with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
   - name: Upload files to S3
     run: aws s3 cp ${{ github.sha}}.zip s3.//jayasriawsbuckt/${{ github.sha }}/
   
        
     
  
